### ISSUE TITLE
build-Sync auto replicate build promotion

### ISSUE THREAD

**Issue by NasAmin** [jfrog/artifactory-user-plugins#211] opened 2018-05-15 11:48 UTC
Hi,

We have started using the buildSync plugin across our two Artifactory servers.
We have enabled push replication for builds. It replicates successfully to the remote instance when a build is published.

How can I set the plugin to automatically sync build promotion as well?

regards,

Nas

**Comment by DarthFennec** [comment] 2018-05-15 16:29
In your `buildSync.json`, adding a `"syncPromotions": true` should do the trick.

**Comment by DarthFennec** [comment] 2018-05-16 20:20
After looking deeper into this, and discussing it with the person who added promotion support to this plugin, I've discovered some more information.

Simply setting `syncPromotions` to `true` should work, but it doesn't, because of an issue with Artifactory. The problem is that Artifactory does not provide the build date as part of the build information, and without that date it's impossible for the plugin to tell if a build has been promoted. There is a [ticket](https://www.jfrog.com/jira/browse/RTFACT-15799) to fix this, and once the ticket goes through, everything should work as expected.

In the meantime, if you also add to the toplevel of the JSON file `"ignoreStartDate": true`, your promotions should sync properly. This is because this tells the plugin to not compare the dates before resyncing a build, which means that even when a build hasn't changed, it'll be synced anyway (but this also applies to promoted builds).

**Comment by NasAmin** [comment] 2018-05-17 11:28
Thanks @DarthFennec. I already have  "ignoreStartDate": true, set in the json file. that does not seem to have any affect.

Here is the full code
```
{
    "ignoreStartDate": true,
    "maxThreads": 10,
    "servers": [
        {
            "key": "tu-server-art",
            "url": "http://tu-server-art.corp.waters.com:8081/artifactory",
            "user": "admin",
            "password": "*****"
        },
        {
            "key": "brasov-slv01",
            "url": "http://brasov-slv01.waters.com:8081/artifactory",
            "user": "admin",
            "password": "*****"
        }
    ],
    "pullConfigs": [
        {
            "key": "NuGet",
            "source": "brasov-slv01",
            "buildNames": [".*"],
            "delete": false,
            "activatePlugins": true,
            "reinsert": false
        },
        {
            "key": "PullFromBrasov",
            "source": "brasov-slv01",
            "buildNames": [".*"],
            "delete": false,
            "activatePlugins": true,
            "reinsert": false
        },
 {
            "key": "PullFromBrasovWithPromotions",
            "source": "brasov-slv01",
            "buildNames": [".*"],
            "delete": false,
            "activatePlugins": false,
            "reinsert": false,
            "syncPromotions": true
        }
    ],
  "pushConfigs": [
        {
            "key": "PushToBrasov",
            "destinations": ["brasov-slv01"],
            "buildNames": [".*"],
            "delete": false,
            "activateOnSave": false
        },
        {
            "key": "PushToBrasovWithPromotions",
            "destinations": ["brasov-slv01"],
            "buildNames": [".*"],
            "delete": false,
            "activateOnSave": false,
            "syncPromotions": true
        },
        {
            "key": "EventPushToBrasov",
            "destinations": ["brasov-slv01"],
            "buildNames": [".*"],
            "delete": false,
            "activateOnSave": true,
            "syncPromotions": true
        }
    ]
}

```

**Comment by NasAmin** [comment] 2018-05-17 11:29
Do I need all of the above configs or can I just have one pull and one push config that does both syncing new builds and promoted builds?

**Comment by DarthFennec** [comment] 2018-05-17 18:50
No, that looks right ... and yes, you can just have one of each in this case.

Mm ... after reading through the code again, I noticed that the promotion sync handling doesn't actually run as a result of the build creation. Now that I think about it, I wouldn't expect the plugin to trigger anyway when a build is promoted, since that's technically modifying the build, not creating it (there's no hook for modifying a build, though). It looks like you'll have to run the REST endpoint for this, then.

**Comment by DarthFennec** [comment] 2019-08-13 21:17
Closing this for now, feel free to reopen if you have any further questions.

**Closed by DarthFennec** 2019-08-13 21:17 UTC
