### ISSUE TITLE
Can data replication be transactional between different RDC(Research Data Center)

### ISSUE THREAD

**Issue by tyrion-1993** [jfrog/artifactory-user-plugins#209] opened 2018-05-09 09:02 UTC
### Transactional data replication ###
_________

when we execute data replication from one RDC to another RDC, we want our file transferred completely before they can be accessed by user. But now we don't have the Plugin to solve this issue, So I 'm here to ask for help!

**Comment by DarthFennec** [comment] 2018-05-09 16:56
I'm not sure I understand the issue. As far as I know, when a file is replicated, it gets fully transferred before it becomes available for access. Unless you mean that you want the entire batch of new files to be replicated before any of those files are available?

It may be helpful if you could describe the specific problem you're having. Thanks!

**Comment by tyrion-1993** [comment] 2018-05-14 02:38
@DarthFennec 
Yes, I want the entire batch of new files to be replicated fully before they can be accessed by users,not a single file.

**Comment by DarthFennec** [comment] 2018-05-14 03:11
I'm pretty certain this can't be done with a plugin. If you could describe the problem (i.e., what's the issue your users are encountering which is caused by batches of files not being replicated atomically?), we might be able to work out an alternate solution.

**Comment by tyrion-1993** [comment] 2018-05-15 01:32
OK. for example,we have batches of files containing file A,file B, file C and an index.xml. Firstly, our users will download the index.xml, then the client will parse the index.xml to get the download URL of the specific file in Artifactory, finally they download the file.

When it comes to files transfer between different RDC(research data center), the index.xml is much smaller and will be transferred quickly,  but our clients can't get the specific file according to the index.xml because the files are under transferring. That's why we want our files transferred thoroughly before they can be accessed by our users. Could you give another solution?

**Comment by DarthFennec** [comment] 2018-05-15 17:54
I see ... this generally isn't a problem for most package types, since Artifactory will not replicate index files, and will instead just regenerate them after the new packages are added. But I suspect you may be using a generic repository for a package type with no explicit support, in which case, Artifactory will not give your index files special treatment. Is this correct?

It is possible to write a plugin that will prevent the index files from replicating, or that will delay the replication to give the other files more time to sync. One of these approaches might work for you, depending on how the index files are generated.

**Comment by tyrion-1993** [comment] 2018-05-16 11:48
Our situation is exactly the same as what you described, we use generic repository to store our all packages.

Is there a method to make Artifactory to replicate index.xml finally each time? Or, how can we write the plugin just like what you said? could you give us some detail guides,  we are very grateful!
@DarthFennec

**Comment by DarthFennec** [comment] 2018-05-16 19:56
There are a few possible approaches that I can think of, depending on how your indexes are generated:

Sometimes, people will write a plugin that recalculates the indexes for their package type automatically, either on a timer or whenever a new package is uploaded. If this is the case for you, all you need to do is prevent the index files from replicating. Then, when packages are replicated, the indexes will be regenerated based on the newly copied packages. This is probably the simplest approach. To prevent the index files from replicating, you can do something like:

``` groovy
replication {
    beforeFileReplication { localRepoPath ->
        skip = localRepoPath.name == 'index.xml'
    }
}
```

The `beforeFileReplication` hook runs prior to each replication of a file. If you set the `skip` variable to `true` within that hook, it tells Artifactory to cancel replication for that file. The documentation for this is [here](https://www.jfrog.com/confluence/display/RTF/User+Plugins#UserPlugins-Replication).

Alternatively, if your indexes are generated by some other means and then deployed to Artifactory (which would make the above approach rather difficult), you could instead delay the replication of the index file. There is no explicit support for this, so doing it is kind of a hack. You'll have to skip replication of the file as above, and at the same time spawn a new thread that does the delay, and then deploys the file:

``` groovy
import org.artifactory.schedule.CachedThreadPoolTaskExecutor

threadPool = ctx.beanForType(CachedThreadPoolTaskExecutor)

replication {
    beforeFileReplication { localRepoPath ->
        if (localRepoPath.name != 'index.xml') return
        skip = true
        threadPool.submit {
            // TODO: delay until all packages are replicated
            // now, deploy the index file
            def conn = new URL("$targetInfo/$localRepoPath.path").openConnection()
            conn.doOutput = true
            conn.requestMethod = 'PUT'
            conn.outputStream << repositories.getContent(localRepoPath).inputStream
            assert conn.responseCode == 201
        }
    }
}
```

(Note that this is provided just as a simple example for the purpose of clarification, and doesn't cover error handling, edge cases where replications overlap, or anything like that. It should probably not be used verbatim in production.)

As you can see, you can use the `targetInfo` context variable to get the URL of the far repository, and then you can use a `PUT` request to deploy the file to that location. This is happening in a separate thread, running in Artifactory's internal thread pool.

Notice how I didn't implement the delay code. There are a number of ways to do the delay, and which one you decide on probably depends on your specific needs. The main problem here is that there is no way to ask Artifactory how many/which artifacts are in the replication batch, so it's difficult to  ensure that you've waited until they're all done.

Some example delay implementations, off the top of my head:

- Just sleep for a hardcoded amount of time. This is the simplest way to do it, but also the least accurate. Sometimes you'll be waiting far longer than necessary, other times the wait won't be long enough. It just depends on the number/size of the other artifacts being replicated.
- Wait until replication "stops", or is idle for a particular amount of time. This would require a global boolean variable that tracks if replication is still going. This would get set to `true` whenever a file starts getting replicated (you can put that at the beginning of the `beforeFileReplication` hook). In the delay implementation, you would have a loop that sets the variable to `false` and then sleeps for a certain period, and then continues the loop unless the variable is still `false`. This way, you wait until there haven't been replication events for a while, which generally means replication is done for now. This can still trigger too early, depending on the size of your files, but it's less likely than the previous case.
- Wait until all files listed in the index are replicated. This is the most "correct" method I expect, but it's also probably the slowest and most complicated. It requires you to parse the index files and get the list of packages, then send requests to the far repository to ensure that it has every file on that list (if not, sleep a while and try again).

Hopefully that helps, and feel free to ask more questions if you need. The user plugin [wiki page](https://www.jfrog.com/confluence/display/RTF/User+Plugins) and [Javadoc](http://repo.jfrog.org/artifactory/oss-releases-local/org/artifactory/artifactory-papi/%5BRELEASE%5D/artifactory-papi-%5BRELEASE%5D-javadoc.jar!/index.html) are excellent resources to find specific information about writing plugins, and this repository has plenty of examples to look at. Good luck!

**Comment by tyrion-1993** [comment] 2018-05-29 13:40
OK! We will try. Thanks your patience~

**Comment by DarthFennec** [comment] 2019-08-13 21:20
Closing this for now. Feel free to reopen if you have any further questions. Thanks!

**Closed by DarthFennec** 2019-08-13 21:20 UTC
