### ISSUE TITLE
filestoreIntegrity plugin fails with error against 6.1.0

### ISSUE THREAD

**Issue by epu** [jfrog/artifactory-user-plugins#241] opened 2018-09-24 15:38 UTC
Installed into a 6.1.0 HA cluster of 3 nodes, but am getting the following error when hitting the plugin end point.

> {
>   "errors" : [ {
>     "status" : 500,
>     "message" : "No signature of method: org.artifactory.storage.db.binstore.dao.BinariesDao.exists() is applicable for argument types: (java.lang.String) values: [00000e11ea23d47e3f402b36dc702fb2fadfaf48]\nPossible solutions: exists(org.artifactory.checksum.ChecksumType, java.lang.String), wait(), equals(java.lang.Object), wait(long), print(java.io.PrintWriter), printf(java.lang.String, java.lang.Object)"
>   } ]
> }

**Comment by DarthFennec** [comment] 2018-09-24 17:48
It works for me and passes our test suite, and this particular issue was fixed a year ago. Are you sure you're using the current release of the plugin?

**Comment by epu** [comment] 2018-09-24 20:57
That was it. Sorry for the churn, my workspace was stuck on the 6f056a2ed9fd1391fe614285c6d3d753452f3e1d revision. Thanks for the help.

**Comment by DarthFennec** [comment] 2018-09-24 21:05
Cool, glad to help. Thanks.

**Comment by DarthFennec** [comment] 2018-09-26 16:46
The exception should cause a stacktrace to log, regardless of anything else. Were you not able to find that? That should give us more information.

Also, did you confirm that the deployed plugin is the same on all of your HA nodes? Sometimes Artifactory has some trouble moving plugins between nodes, so if you only updated it on one node, it's possible that it hasn't automatically transferred to the others.

**Comment by epu** [comment] 2018-09-26 17:09
> Also, did you confirm that the deployed plugin is the same on all of your HA nodes?
Did, but double checked to be sure. Looks like it distributed to nodes ok.

**Comment by epu** [comment] 2018-09-26 17:41
> The exception should cause a stacktrace to log, regardless of anything else. Were you not able to find that? That should give us more information.

Found it on one of the HA secondary nodes. I'll pop it into a gist.

**Comment by DarthFennec** [comment] 2018-09-26 19:52
```
...
at filestoreIntegrity$_run_closure1$_closure2$_closure3.doCall(filestoreIntegrity.groovy:35)
...
```

So it's line 35. That's [here](https://github.com/jfrog/artifactory-user-plugins/blob/5839ff23a5031bf39d27875fc099bc7c961b3f97/filestore/filestoreIntegrity/filestoreIntegrity.groovy#L35) (old version):

``` groovy
binstore.exists(it) && !new File(bindir, "${it[0..1]}/$it").exists()
```

Or, [here](https://github.com/jfrog/artifactory-user-plugins/blob/master/filestore/filestoreIntegrity/filestoreIntegrity.groovy#L35) (current version):

``` groovy
existsInDatabase(binstore, it) && !new File(bindir, "${it[0..1]}/$it").exists()
```

The error reports `No BinariesDao.exists() is applicable for argument types: (java.lang.String)`, which means it's a call to a `BinariesDao::exists(String)`. That last call in both lines is to `File::exists()`, so that doesn't match. There is no line in the stacktrace from inside the `existsInDatabase` function, which means the error doesn't come from there. The only possibility is the `binstore.exists(it)` call in the old version of the plugin. Nothing in the current version matches.

I'm not really sure where to go from here. It's clear that at the time this stacktrace was logged, at least this node was still running an old version of the plugin. However, if you had already confirmed that all nodes had the current version before doing a rolling restart, that should have been more than enough to prevent this issue. I guess I would try double checking and then doing the restart again. If that doesn't work, you could try removing the plugin entirely, restarting, and then installing the plugin fresh.

**Comment by epu** [comment] 2018-09-26 20:04
@DarthFennec - thanks for the stack trace analysis and advice. I can confirm that the files are the same on each node. I'll try bringing the app completely down, and I'll try the plugin removal with restart, and report back.

**Comment by epu** [comment] 2018-09-26 20:15
@DarthFennec - a complete application stop and start runs this ok. I didn't have to uninstall and restart. Bad news is that I don't understand why that worked. Operator error? Thanks again for your help.

**Comment by DarthFennec** [comment] 2018-09-26 20:30
I don't really understand either. I doubt the rolling restart prevented the nodes from updating properly somehow, since that approach has worked for me in this situation in the past. Operator error sounds plausible, and it happens to the best of us (there have been plenty of times where I'll miss a step or do things in the wrong order without realizing it). Whatever the case, I'm glad it's working now. Let us know if there are any more issues. Thanks!

**Closed by DarthFennec** 2018-09-26 20:30 UTC
