### ISSUE TITLE
How do the unit tests run?

### ISSUE THREAD

**Issue by NetAppBlueDevil** [jfrog/artifactory-user-plugins#342] opened 2020-11-04 16:12 UTC
I have user plugins that I cannot directly contribute here, but I would like to follow the pattern for being able to implement the unit tests I see here.  I see that you are using the Spock framework.  Is there a simple example build file pattern that is available that I could utilize if I just want to set up a basic /test folder alongside my existing plugins ?

**Comment by DarthFennec** [comment] 2020-11-04 21:06
First of all, apologies, this is a bit messy and suboptimal.

Internally, we use a custom framework called Lilypad to develop and run these tests. It's a Gradle project with specialized tasks for creating and using test environments. I'd like to just link that to you, but it's not currently publicly available. Probably the next best thing is [`artifactory-user-plugins-devenv`](https://github.com/jfrog/artifactory-user-plugins-devenv), which is the project Lilypad is meant to replace, so they're partially inter-compatible (Lilypad supports more features, but if you don't use those features they can both run the same tests).

This should be fine for something simple like what you're looking for, but note that we stopped updating/supporting this project in mid 2017, so there's no guarantee it'll work as-is. You might need to do some tweaking if you run into problems.

If you have any issues, let me know, and I'll try to help if I can.

**Comment by NetAppBlueDevil** [comment] 2020-11-04 21:11
OK.  I have some basic familiarity with gradle.  Let me check the Spock site and see if they have a basic example, since all I’m trying to do is execute tests with self contained mock objects.  Thanks for the pointer to he devenv, I’ll check that too

**Comment by jfrog-aparicio** [comment] 2020-11-05 21:08
Duplicate of #293

**Closed by jfrog-aparicio** 2020-11-05 21:08 UTC
Labels: duplicate
