### ISSUE TITLE
The Webhook plugin does not work with Java 11

### ISSUE THREAD

**Issue by rohanrasane** [jfrog/artifactory-user-plugins#255] opened 2018-12-12 19:16 UTC
The Webhook plugin uses JSONSlurper method and this method always throws java.lang.ClassCastException

**Comment by DarthFennec** [comment] 2019-04-18 16:23
I can't reproduce, it works fine in Java 11 for me. Could you post the exact error and stacktrace that you're getting? That should help us look into it further.

**Comment by ankushchadha** [comment] 2019-05-22 21:15
Hi @rohanrasane, we are closing this issue since we were unable to reproduce the issue. Feel free to re-open the issue with the requested info. Thanks

**Closed by ankushchadha** 2019-05-22 21:15 UTC
